language: dart

dart:
  - dev

dart_task:
  - test: -p vm
  - dartfmt
  - dartanalyzer

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
