language: dart

addons:
  chrome: stable

dart:
  - dev

jobs:
  include:
  - script: pub run --enable-experiment=non-nullable test
  - script: pub run --enable-experiment=non-nullable test -p chrome
  - dart_task: dartfmt
  - dart_task:
      dartanalyzer: --enable-experiment=non-nullable --fatal-infos --fatal-warnings .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
