language: dart

dart:
- dev

jobs:
  include:
  - script: pub run --enable-experiment=non-nullable test
  - script: pub run --enable-experiment=non-nullable test -p chrome
  - dart_task:
      dartfmt -n .
  - dart_task:
      dartanalyzer: --enable-experiment=non-nullable --fatal-infos --fatal-warnings .

# Only building master means that we don't run two builds for each pull request.
# Temporarily adding `null_safety`
branches:
  only: [master]

cache:
  directories:
  - $HOME/.pub-cache
