include: package:lints/recommended.yaml

analyzer:
  language:
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types: true
    - avoid_dynamic_calls: true
    - directives_ordering: true
    - sort_pub_dependencies: true
