include: package:lints/recommended.yaml

analyzer:
  language:
    strict-raw-types: true
  errors:
    deprecated_member_use_from_same_package: ignore

linter:
  rules:
    - always_declare_return_types
    #- avoid_dynamic_calls
    - directives_ordering
    - sort_pub_dependencies
